package main

// gitmoji maps short codes to emoji + descriptions, for emoji-based
// commit prefixes. Users type ":" to trigger gitmoji suggestions.
var gitmojiList = []struct {
	code string // short code typed by user
	emoji string // the emoji character
	desc  string // human description
}{
	{"sparkles", "✨", "introduce new features"},
	{"bug", "🐛", "fix a bug"},
	{"fire", "🔥", "remove code or files"},
	{"art", "🎨", "improve structure / format of the code"},
	{"zap", "⚡️", "improve performance"},
	{"memo", "📝", "write docs"},
	{"rocket", "🚀", "deploy stuff"},
	{"lipstick", "💄", "add or update UI and style files"},
	{"tada", "🎉", "begin a project"},
	{"white-check-mark", "✅", "add or update tests"},
	{"lock", "🔒", "fix security issues"},
	{"closed-lock-with-key", "🔐", "add or update secrets"},
	{"bookmark", "🔖", "release / version tags"},
	{"rotating-light", "🚨", "fix compiler / linter warnings"},
	{"construction", "🚧", "work in progress"},
	{"green-heart", "💚", "fix CI build"},
	{"arrow-down", "⬇️", "downgrade dependencies"},
	{"arrow-up", "⬆️", "upgrade dependencies"},
	{"pushpin", "📌", "pin dependencies to specific versions"},
	{"construction-worker", "👷", "add or update CI build system"},
	{"chart-with-upwards-trend", "📈", "add or update analytics or track code"},
	{"recycle", "♻️", "refactor code"},
	{"hammer", "🔧", "add or update configuration files"},
	{"globe-with-meridians", "🌐", "internationalization and localization"},
	{"pencil", "✏️", "fix typos"},
	{"poop", "💩", "write bad code that needs to be improved"},
	{"rewind", "⏪️", "revert changes"},
	{"twisted-rightwards-arrows", "🔀", "merge branches"},
	{"package", "📦", "add or update compiled files or packages"},
	{"alien", "👽", "update code due to external API changes"},
	{"truck", "🚚", "move or rename resources"},
	{"label", "🏷️", "add or update types"},
	{"speech-balloon", "💬", "add or update text and literals"},
	{"card-file-box", "🗃️", "perform database related changes"},
	{"loud-sound", "🔊", "add or update logs"},
	{"mute", "🔇", "remove logs"},
	{"busts-in-silhouette", "👥", "add or update contributors"},
	{"children-crossing", "🚸", "improve user experience / usability"},
	{"building-construction", "🏗️", "make architectural changes"},
	{"iphone", "📱", "work on responsive design"},
	{"clown-face", "🤡", "mock things"},
	{"egg", "🥚", "add or update an easter egg"},
	{"see-no-evil", "🙈", "add or update a .gitignore"},
	{"camera-flash", "📸", "add or update snapshots"},
	{"alembic", "⚗️", "perform experiments"},
	{"mag", "🔍", "improve SEO"},
	{"wheelchair", "♿️", "improve accessibility"},
	{"bulb", "💡", "add or update comments in source code"},
	{"beers", "🍻", "write code drunkenly"},
	{"speech-balloon", "💬", "update text and literals"},
	{"card-index", "📇", "perform database related changes"},
	{"heavy-plus-sign", "➕", "add a dependency"},
	{"heavy-minus-sign", "➖", "remove a dependency"},
	{"wrench", "🔧", "add or update configuration files"},
	{"adhesive-bandage", "🩹", "simple fix for a non-critical issue"},
	{"compass", "🧭", "update or add navigation"},
	{"bricks", "🧱", "infra related changes"},
	{"technologist", "🧑‍💻", "improve developer experience"},
	{"money-with-wings", "💸", "add or update sponsorship"},
	{"thread", "🧵", "add or update multithreading"},
	{"cold-face", "🥶", "fix a freeze"},
}
